### ISSUE TITLE
rake fails on expectations to specific cocoa revisions that don't exist

### ISSUE THREAD

**Issue by patrickhno** [mobiruby/mobiruby-ios#36]
rake fails on expectations to specific cocoa revisions that don't exist:

```
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
fatal: reference is not a tree: 0458b0373659f8d0176986a503dab2f9fee26e62
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
fatal: reference is not a tree: 0458b0373659f8d0176986a503dab2f9fee26e62
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
fatal: reference is not a tree: 0458b0373659f8d0176986a503dab2f9fee26e62
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
fatal: reference is not a tree: 0458b0373659f8d0176986a503dab2f9fee26e62
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
```

How to reproduce:

```
git clone https://github.com/mobiruby/mobiruby-ios.git
cd mobiruby-ios/
rake
```

**Comment by patrickhno** [comment]
On rerun (rake):

```

rake aborted!
Can't find /Users/patrick/mobiruby-ios/submodules/mruby-cocoa/mrbgem.rake
/Users/patrick/mobiruby-ios/submodules/mruby/tasks/mruby_build_gem.rake:19:in `gem'
tasks/../build-libmruby.rb:52:in `block (3 levels) in <top (required)>'
/Users/patrick/mobiruby-ios/submodules/mruby/tasks/mruby_build.rake:85:in `instance_eval'
/Users/patrick/mobiruby-ios/submodules/mruby/tasks/mruby_build.rake:85:in `initialize'
/Users/patrick/mobiruby-ios/submodules/mruby/tasks/mruby_build.rake:201:in `initialize'
tasks/../build-libmruby.rb:31:in `new'
tasks/../build-libmruby.rb:31:in `block (2 levels) in <top (required)>'
tasks/../build-libmruby.rb:30:in `each'
tasks/../build-libmruby.rb:30:in `block in <top (required)>'
tasks/../build-libmruby.rb:24:in `each'
tasks/../build-libmruby.rb:24:in `<top (required)>'
submodules/mruby/Rakefile:14:in `load'
submodules/mruby/Rakefile:14:in `<top (required)>'
tasks/build.rake:24:in `load'
tasks/build.rake:24:in `<top (required)>'
/Users/patrick/mobiruby-ios/Rakefile:2:in `load'
/Users/patrick/mobiruby-ios/Rakefile:2:in `<top (required)>'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/rake_module.rb:25:in `load'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/rake_module.rb:25:in `load_rakefile'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:589:in `raw_load_rakefile'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:89:in `block in load_rakefile'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:88:in `load_rakefile'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:72:in `block in run'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
(See full trace by running task with --trace)
```

**Comment by patrickhno** [comment]
I see some fatal warnings on the first run, so this is the complete output:

```

git submodule init
Submodule 'submodules/ios-sim' (https://github.com/phonegap/ios-sim.git) registered for path 'submodules/ios-sim'
Submodule 'submodules/libffi' (https://github.com/mobiruby/libffi.git) registered for path 'submodules/libffi'
Submodule 'submodules/libuv' (https://github.com/joyent/libuv.git) registered for path 'submodules/libuv'
Submodule 'submodules/mobiruby-common' (https://github.com/mobiruby/mobiruby-common.git) registered for path 'submodules/mobiruby-common'
Submodule 'submodules/mruby' (https://github.com/mruby/mruby.git) registered for path 'submodules/mruby'
Submodule 'submodules/mruby-cfunc' (https://github.com/mobiruby/mruby-cfunc.git) registered for path 'submodules/mruby-cfunc'
Submodule 'submodules/mruby-cocoa' (https://github.com/mobiruby/mruby-cocoa.git) registered for path 'submodules/mruby-cocoa'
Submodule 'submodules/mruby-digest' (https://github.com/iij/mruby-digest.git) registered for path 'submodules/mruby-digest'
Submodule 'submodules/mruby-http' (https://github.com/mattn/mruby-http.git) registered for path 'submodules/mruby-http'
Submodule 'submodules/mruby-json' (https://github.com/mattn/mruby-json.git) registered for path 'submodules/mruby-json'
Submodule 'submodules/mruby-pack' (https://github.com/iij/mruby-pack.git) registered for path 'submodules/mruby-pack'
Submodule 'submodules/mruby-sqlite3' (https://github.com/mobiruby/mruby-sqlite3.git) registered for path 'submodules/mruby-sqlite3'
Submodule 'submodules/mruby-uv' (https://github.com/mattn/mruby-uv.git) registered for path 'submodules/mruby-uv'
Cloning into 'submodules/ios-sim'...
remote: Counting objects: 376, done.
remote: Compressing objects: 100% (221/221), done.
remote: Total 376 (delta 222), reused 284 (delta 137)
Receiving objects: 100% (376/376), 62.68 KiB, done.
Resolving deltas: 100% (222/222), done.
Submodule path 'submodules/ios-sim': checked out 'ef30c400c732b73451c7683df1a8088167ae3a24'
Cloning into 'submodules/libffi'...
remote: Counting objects: 7862, done.
remote: Compressing objects: 100% (3332/3332), done.
remote: Total 7862 (delta 4415), reused 7723 (delta 4301)
Receiving objects: 100% (7862/7862), 5.54 MiB | 476 KiB/s, done.
Resolving deltas: 100% (4415/4415), done.
Submodule path 'submodules/libffi': checked out 'f308faf1eabaf8dc24966ab17fbf94368f46b9c7'
Cloning into 'submodules/libuv'...
remote: Counting objects: 15912, done.
remote: Compressing objects: 100% (8994/8994), done.
remote: Total 15912 (delta 9773), reused 12834 (delta 6864)
Receiving objects: 100% (15912/15912), 8.21 MiB | 470 KiB/s, done.
Resolving deltas: 100% (9773/9773), done.
Submodule path 'submodules/libuv': checked out 'ab935a25a5f2709105717005de70655bf8291e36'
Cloning into 'submodules/mobiruby-common'...
remote: Counting objects: 85, done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 85 (delta 28), reused 82 (delta 25)
Unpacking objects: 100% (85/85), done.
Submodule path 'submodules/mobiruby-common': checked out 'e1275d327641a60d444e64de618dfa9d79ba8a4f'
Cloning into 'submodules/mruby'...
remote: Counting objects: 15071, done.
remote: Compressing objects: 100% (7606/7606), done.
remote: Total 15071 (delta 9268), reused 12931 (delta 7230)
Receiving objects: 100% (15071/15071), 3.79 MiB | 464 KiB/s, done.
Resolving deltas: 100% (9268/9268), done.
Submodule path 'submodules/mruby': checked out 'c8c4dfe426da121549f73fd776d0696a701db6b6'
Cloning into 'submodules/mruby-cfunc'...
remote: Counting objects: 957, done.
remote: Compressing objects: 100% (407/407), done.
remote: Total 957 (delta 552), reused 936 (delta 537)
Receiving objects: 100% (957/957), 226.46 KiB | 361 KiB/s, done.
Resolving deltas: 100% (552/552), done.
Submodule path 'submodules/mruby-cfunc': checked out '4633749baaea8049dc39f14e4310920603570468'
Cloning into 'submodules/mruby-cocoa'...
remote: Counting objects: 682, done.
remote: Compressing objects: 100% (268/268), done.
remote: Total 682 (delta 387), reused 682 (delta 387)
Receiving objects: 100% (682/682), 329.72 KiB | 283 KiB/s, done.
Resolving deltas: 100% (387/387), done.
fatal: reference is not a tree: 0458b0373659f8d0176986a503dab2f9fee26e62
Cloning into 'submodules/mruby-digest'...
remote: Counting objects: 51, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 51 (delta 19), reused 43 (delta 11)
Unpacking objects: 100% (51/51), done.
Submodule path 'submodules/mruby-digest': checked out 'ebe896cbb8bce57578ba153bd8e4fb055436483d'
Cloning into 'submodules/mruby-http'...
remote: Counting objects: 315, done.
remote: Compressing objects: 100% (195/195), done.
remote: Total 315 (delta 159), reused 273 (delta 117)
Receiving objects: 100% (315/315), 63.07 KiB, done.
Resolving deltas: 100% (159/159), done.
Submodule path 'submodules/mruby-http': checked out '57311df7bad40c622dbb5aa5f50a3276321bd148'
Cloning into 'submodules/mruby-json'...
remote: Counting objects: 114, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 114 (delta 40), reused 84 (delta 10)
Receiving objects: 100% (114/114), 19.80 KiB, done.
Resolving deltas: 100% (40/40), done.
Submodule path 'submodules/mruby-json': checked out 'e412158e5206238c5d4f2b542ea4e04940083c87'
Cloning into 'submodules/mruby-pack'...
remote: Counting objects: 75, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 75 (delta 33), reused 70 (delta 28)
Unpacking objects: 100% (75/75), done.
Submodule path 'submodules/mruby-pack': checked out '858d67c1549a93eec4b36e5c94e22b21f55634b8'
Cloning into 'submodules/mruby-sqlite3'...
remote: Counting objects: 183, done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 183 (delta 82), reused 143 (delta 42)
Receiving objects: 100% (183/183), 22.20 KiB, done.
Resolving deltas: 100% (82/82), done.
Submodule path 'submodules/mruby-sqlite3': checked out 'cf978b3efe36c71ef0fd67f3ccc8416a678490c1'
Cloning into 'submodules/mruby-uv'...
remote: Counting objects: 847, done.
remote: Compressing objects: 100% (397/397), done.
remote: Total 847 (delta 459), reused 833 (delta 447)
Receiving objects: 100% (847/847), 122.98 KiB, done.
Resolving deltas: 100% (459/459), done.
Submodule path 'submodules/mruby-uv': checked out '4facd5903ecc968e282fd6aa515a2daa93980bed'
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
fatal: reference is not a tree: 0458b0373659f8d0176986a503dab2f9fee26e62
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
fatal: reference is not a tree: 0458b0373659f8d0176986a503dab2f9fee26e62
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
fatal: reference is not a tree: 0458b0373659f8d0176986a503dab2f9fee26e62
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
fatal: reference is not a tree: 0458b0373659f8d0176986a503dab2f9fee26e62
Unable to checkout '0458b0373659f8d0176986a503dab2f9fee26e62' in submodule path 'submodules/mruby-cocoa'
rake aborted!

tasks/build.rake:21:in `block in <top (required)>'
tasks/build.rake:9:in `block in retry_if'
tasks/build.rake:7:in `times'
tasks/build.rake:7:in `each'
tasks/build.rake:7:in `retry_if'
tasks/build.rake:20:in `<top (required)>'
/Users/patrick/mobiruby-ios/Rakefile:2:in `load'
/Users/patrick/mobiruby-ios/Rakefile:2:in `<top (required)>'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/rake_module.rb:25:in `load'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/rake_module.rb:25:in `load_rakefile'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:589:in `raw_load_rakefile'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:89:in `block in load_rakefile'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:88:in `load_rakefile'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:72:in `block in run'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
/Users/patrick/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
(See full trace by running task with --trace)
```

**Comment by masuidrive** [comment]
I mistook. Could you pull and try again?

**Comment by patrickhno** [comment]
Yes, this is better, thanks!
